### PR TITLE
Fix GH-666: Make category options into key/value

### LINKED ISSUE #666: Explore - XHR request should include `q=*` not `q=all`
Currently, the explore page issues an XHR request with a query string of `q=all` which actually does a search for projects that include `all` in the metadata. This should be changed to either `q=*` or simply drop that query string parameter altogether.

### PR DESCRIPTION
**Pull request by mewtaylor**
so that we can store the query string with the tab name, since it's not the same in every instance. fixes #666, and makes a couple other style tweaks.

### CODE REVIEW

File: src/views/explore/explore.jsx [hunk 1]
```diff
@@ -80,34 +86,28 @@ var Explore = injectIntl(React.createClass({
...
-                    </a>;
-        if (this.props.category === type) {
-            allBubble = <a href={'/explore/' + this.props.itemType+'/' + type + '/'}>
-                        <li className='active'>
-                            <FormattedMessage id={'general.' + type} />
-                        </li>
-                    </a>;
-        }
-        return allBubble;
+        let classes = classNames({
```
Comment (thisandagain) [inline src/views/explore/explore.jsx]: This will break, no?

**Comment by thisandagain** [comment]
@mewtaylor @rschamp Worried about our use of `let` here until we have moved over to Babel (not this iteration). Should this be rolled back?

**Comment by mewtaylor** [comment]
@thisandagain you're correct – see https://github.com/LLK/scratch-www/commit/9a037fda818c415097df26e9b6eed4f9c5078924
