### PR TITLE
Fix GH-[683,705,712,797]: Updates to registration UX for teachers

### LINKED ISSUE #683: Teacher Registration - I don't see validations (e.g. for username already exists) until I click "Next"
Staging, Chrome

In teacher registration, I don't see the validation that I'm trying to sign up with an extant username until I click the Next button:
screen shot 2016-07-06 at 3 13 52 pm

In our other join flow, you see the verification that username exists right after you type it:
screen shot 2016-07-06 at 3 13 44 pm

Most of the validations for the fields in the teacher registration flow are not triggered until you click "next".

However, the phone number validation seems to be as soon as the system detects that the field has been typed in but the existing number isn't valid... e.g. if I type my real phone number, it comes up as "invalid" until the last digit... (which doesn't seem like obviously the best behaviour to me? Maybe it could wait until the user deactivates the field or otherwise signals they're "done" typing):
screen shot 2016-07-06 at 3 49 00 pm

Ideally, I think we would be consistent with when validations are triggered for fields across the platform. /cc @carljbowman

### PR DESCRIPTION
**Pull request by mewtaylor**
1. Phone too long validation occurs before submit now.
2. Organization “other” type is now being required
3. Organization type required now shows up at the same time as other organization validation errors
4. Username check now occurs earlier, on blur rather than on submit

Fixes #683, #705, #712, #797.

### Test Cases ###
* Try to register with a pre-existing username. It should show you an error after you focus out from the username field
* Try to type a phone number that's too long – it should show an error and prevent moving to the next step
* Try to submit without choosing an organization type or an organization name. The organization type error should appear
* Try to choose "Other" for organization without putting anything in the black input. An error should appear, and prevent you from moving to the next step.

### CODE REVIEW

File: src/components/registration/steps.jsx [hunk 1]
```diff
@@ -473,8 +489,21 @@ module.exports = {
         onChooseOrganization: function (name, values) {
             this.setState({otherDisabled: values.indexOf(this.organizationL10nStems.indexOf('orgChoiceOther')) === -1});
         },
-        onValidSubmit: function (formData, reset, invalidate) {
+        validateOrganizationType: function (formData) {
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: If this were a regular validation for the organization CheckboxGroup, then wouldn't it automatically be run `onSubmit` (and ahead of `onValidSubmit`)?

File: src/components/registration/steps.jsx [hunk 2]
```diff
@@ -82,38 +82,53 @@ module.exports = {
...
                 }
             }.bind(this));
         },
+        onUsernameBlur: function (event) {
+            this.validateUsername(event.currentTarget.value);
+        },
+        onValidSubmit: function (formData) {
+            this.setState({waiting: true});
+            this.validateUsername(formData.user.username);
+            this.setState({waiting: false});
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: Here `validateUsername` is treated like it's synchronous, but that method uses an asynchronous API call. The `waiting` state change and `onNextStep` calls should happen in a callback. If this does work locally, it's because `this.validateUsername(formData.user.username)` returns in time for the rest of the function to continue due to the speed of the local connection. It would surely break running remotely.

File: src/components/registration/steps.jsx [hunk 3]
```diff
@@ -82,38 +82,53 @@ module.exports = {
...
                         'user.username': formatMessage({id: 'registration.validationUsernameVulgar'})
                     });
+                    return false;
                 case 'invalid username':
                 default:
-                    return invalidate({
+                    this.refs.form.refs.formsy.updateInputsWithError({
                         'user.username': formatMessage({id: 'registration.validationUsernameInvalid'})
                     });
+                    return false;
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: Does the return of `true`/`false` have any effect, or could this be reduced to just return the statement above?

File: src/components/registration/steps.jsx (hunk 2 above)
Comment (mewtaylor) [inline src/components/registration/steps.jsx]: whoops – meant to put a callback in there instead. 👍

File: src/components/registration/steps.jsx (hunk 3 above)
Comment (mewtaylor) [inline src/components/registration/steps.jsx]: once I add the callback (which I forgot to do), `true/false` handles the difference between `onValidSubmit` and `onSubmit`. Since we don't want to call `onNextStep` for `onSubmit`, but do for `onValidSubmit`.

File: src/components/registration/steps.jsx (hunk 1 above)
Comment (mewtaylor) [inline src/components/registration/steps.jsx]: IIRC the `required` prop does not work as we expect in this case for `CheckboxGroup`. I'm not sure if we could implement a validator in `validations.jsx` directly, but will take a look.

File: src/components/registration/steps.jsx [hunk 4]
```diff
@@ -494,7 +515,7 @@ module.exports = {
                                  tipContent={formatMessage({id: 'registration.nameStepTooltip'})} />
                     </p>
                     <Card>
-                        <Form onValidSubmit={this.onValidSubmit}>
+                        <Form onValidSubmit={this.onValidSubmit} onSubmit={this.onSubmit}>
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: Now this can be `onValidSubmit={this.props.onNextStep}` and the `onValidSubmit` method can go away.

File: src/components/registration/steps.jsx [hunk 5]
```diff
@@ -82,38 +82,63 @@ module.exports = {
...
                 default:
-                    return invalidate({
+                    this.refs.form.refs.formsy.updateInputsWithError({
                         'user.username': formatMessage({id: 'registration.validationUsernameInvalid'})
                     });
+                    break;
+                }
+
+                if (typeof callback !== 'undefined') {
+                    callback(isValid);
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: One last suggestion that I think is just stylistic — if you make `callback` optional on the first line of the function with `callback = callback || function () {};`, then you can always just `return callback(true/false)` without checking the type of `callback`.

If the reason you changed the style here was to avoid repeating the `if (typeof callback !== 'undefined') {...}` in every `case`, then this would allow you to just return within each `case` too. Personally I find the inline returns more readable than the fall-through style, since you know what happens as soon as you see a `return`.

**Comment by jwzimmer** [comment]
Testing, Staging @mewtaylor 

**Chrome Version 52.0.2743.82 (64-bit), Mac OS X El Capitan**
- I'm still seeing the phone number issue from #712; although now I don't see the validation when I click "Next", so I can enter a too-long phone number and get to the next step.
out
- I noticed I can type in the Type of Organization > Other field when it's checked, then uncheck it, and whatever I typed stays. This seems not ideal to me. It didn't seem to cause an error at the end of registration, but I don't think it's the standard behaviour.
screen shot 2016-08-22 at 11 00 59 am
- The Type of Organization does occur at the same time as the other validations on that page now, so that's working.

**Comment by jwzimmer** [comment]
Testing, Staging
@mewtaylor 

**Safari Version 9.1.2 (11601.7.7), Mac OS X El Capitan**
* Just from typing in a few known usernames to test out the validation (I didn't click next, just clicked in between username and password fields, I got this error:
screen shot 2016-08-22 at 5 58 21 pm
screen shot 2016-08-22 at 5 57 02 pm

**Comment by jwzimmer** [comment]
In Safari on Mac (see comment above), I'm still seeing this error after clearing cache and history. The repro steps are: go to `educators/register`, click Next, put your cursor in username field, click Next again.
screen shot 2016-08-23 at 1 30 44 pm

**Comment by mewtaylor** [comment]
@jwzimmer the issue appears to be that it attempts to check the empty username once you engage the username field, and is finding an empty string. I'm not 100% sure, but I *think* that this would've existed before this particular fix, since all this fix does is add a check on focus out.

Adding an additional check to make sure the username check has a value at all before sending it to the server seems reasonable, and could be done for the release, if desired.

**Comment by jwzimmer** [comment]
@mewtaylor well, since the validation ("oops...") goes away if you fill out the fields, and it doesn't seem to cause an error at the end of registration, I'm fine with opening a separate case for it.

**Comment by mewtaylor** [comment]
@jwzimmer sounds good to me!

**Comment by jwzimmer** [comment]
@mewtaylor Just to clarify - it does seem like this error is more likely to be encountered by a user because of this PR, right? Since the username check happens on blur, rather than clicking "Next", the user is more likely to encounter this error (e.g. if they enter a username, then start typing a password, then clear the username because they see the "this username is already in use" validation, then finish the password...)?

**Comment by mewtaylor** [comment]
@jwzimmer yeah that is true, it'll be more apparent in that case

**Comment by jwzimmer** [comment]
@mewtaylor Okay, thanks. I think separate case is fine, but I think it would be good to get to https://github.com/LLK/scratch-www/issues/872 in the next milestone... what do you think?

**Comment by mewtaylor** [comment]
@jwzimmer totally agree!

**Comment by jwzimmer** [comment]
Just wanted to doublecheck the test cases one last time, Chrome 52 on Mac OS X El Capitan:
- [x] Try to register with a pre-existing username. It should show you an error after you focus out from the username field
- [x] Try to submit without choosing an organization type or an organization name. The organization type error should appear
- [x] Try to choose "Other" for organization without putting anything in the black input. An error should appear, and prevent you from moving to the next step.
