### PR TITLE
Fix gh-1154: Join Us Section on Developers Page

### LINKED ISSUE #1154: Add jobs link to Developers Page
The developers page should probably point to our job openings. 

Above the 'Donate' Section, add a new section called 'Join Us', text below:

**Join Us** [same font / size as the 'Donate' header] 

We're a diverse group of educators, designers, and engineers, who work together in a playful, creative environment full of LEGO bricks, craft materials, and maker tools. We strongly value diversity, collaboration, and respect in the workplace. If you're interested in joining us, take a look at our open positions on our [Jobs Page](https://scratch.mit.edu/jobs/), or send us an email at jobs+developers@scratch.mit.edu

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #1154 

## Test cases:
- New 'Join Us' button should be present with the other navigational buttons on the page.
- New 'Join Us' section should be present above 'Donate' section.
- Text "Jobs Page" in 'Join Us' content should link to https://scratch.mit.edu/jobs/
- Text "jobs+developers@scratch.mit.edu" in 'Join Us' content should link to mailto:jobs+developers@scratch.mit.edu

### CODE REVIEW

**Comment by thisandagain** [comment]
Thanks @TheGrits !

**Comment by TheGrits** [comment]
@thisandagain No problem!

**Comment by thisandagain** [comment]
@chrisgarrity Ping

File: src/views/developers/developers.jsx [hunk 1]
```diff
@@ -157,6 +162,12 @@ var Developers = React.createClass({
                         </FlexRow>
                     </section>
 
+                    <section id="join">
+                        <span className="nav-spacer"></span>
+                        <h2><FormattedMessage id='developers.joinTitle' /></h2>
+                        <p><FormattedMessage id='developers.joinBody' /></p>
```
Comment (chrisgarrity) [inline src/views/developers/developers.jsx]: @TheGrits This looks great. One minor issue. The developers.joinBody needs to be included with a FormattedHTMLMessage instead of FormattedMessage because the text includes HTML tags. Other than that, it looks good.

Comment (TheGrits) [inline src/views/developers/developers.jsx]: @chrisgarrity Thanks for pointing out that gotcha, I'll fix it right now.

**Comment by TheGrits** [comment]
@chrisgarrity Done!
