### PR TITLE
Fix gh-1218: Community Moderator Page

### LINKED ISSUE #1218: Add "Community Moderator" to jobs page
We're hiring a new moderator - and would like to revive the Scratch "Community Moderator" job description as soon as possible. 

### To Do
- [ ] Create new page with job description (`/jobs/moderator`)
- [ ] Update `/jobs` page with new link
- [ ] Remove "Senior Back-end Engineer" from `/jobs` page

### Reference
https://gist.github.com/thisandagain/f30219508c049e7666cdd89fbc1fdd87

---
Moved from LLK/scratchr2#4508
/cc @SpeakkVisually

### PR DESCRIPTION
**Pull request by TheGrits**
Should resolve #1218 

## Test cases:
- Back-End Engineer position removed from jobs page
- Community Moderator position added to jobs page
- Community Moderator page added at `/jobs/moderator`
- All links should be functional on the Community Moderators page (Twitter links, create link, mailto link)

### CODE REVIEW

**Comment by TheGrits** [comment]
@thisandagain Travis just blew up, but it looks like the PR itself passed. It appears that the localization strings are inaccessible.

**Comment by TheGrits** [comment]
@thisandagain Just saw your comment on the issue, I'll remove the sharing links right now.

File: src/views/jobs/moderator/moderator.jsx [hunk 1]
```diff
@@ -0,0 +1,94 @@
+var React = require('react');
+var render = require('../../lib/render.jsx');
```
Comment (thisandagain) [inline src/views/jobs/moderator/moderator.jsx]: All of these paths are off my one level as you are nested inside of the `jobs` view. Were you able to get this to build locally?

Comment (TheGrits) [inline src/views/jobs/moderator/moderator.jsx]: @thisandagain Nope, I have a Chromebook, so I don't have the capabilities to do so. (And I still don't have a large enough SD card for my Raspberry Pi ☹️) Sorry about that, I'll fix it.

**Comment by TheGrits** [comment]
@thisandagain Done! (Also, that fixed Travis, w00t!)

File: src/routes.json [hunk 2]
```diff
@@ -181,6 +181,13 @@
         "title": "Jobs"
     },
     {
+        "name": "jobs-moderator",
+        "pattern": "^jobs/moderator/?$",
+        "routeAlias": "/jobs/moderator/?$",
```
Comment (thisandagain) [inline src/routes.json]: I think we want the `routeAlias` to simply be `/jobs` (see "microworlds" pattern below).

Comment (TheGrits) [inline src/routes.json]: Sounds good, I'll hop to it!

**Comment by thisandagain** [comment]
I think that covers everything for me! Assigning to @mewtaylor for a second set of eyes.

File: src/routes.json [hunk 3]
```diff
@@ -181,6 +181,13 @@
         "title": "Jobs"
     },
     {
+        "name": "jobs-moderator",
+        "pattern": "^jobs/moderator/?$",
```
Comment (mewtaylor) [inline src/routes.json]: This needs an extra `/` before `jobs`: I think it should be `^/jobs/moderator/?$`

File: src/views/jobs/jobs.jsx [hunk 4]
```diff
@@ -31,16 +31,16 @@ var Jobs = React.createClass({
...
                         <ul>
                             <li>
-                                <a href="http://bit.ly/2f5hABE">
-                                    Trust &amp; Safety Manager
+                                <a href="/jobs/moderator">
+                                    Community Moderator
                                 </a>
                                 <span>
-                                    (MIT Media Lab, Cambridge, MA)
+                                    MIT Media Lab, Cambridge, MA (or Remote)
```
Comment (mewtaylor) [inline src/views/jobs/jobs.jsx]: I think it'd be good to make this be `(MIT Media Lab, Cambridge, MA or Remote)` to match with the parentheses of the Trust & Safety Manager

**Comment by TheGrits** [comment]
@mewtaylor Done!
