### PR TITLE
Fix gh-938: Update Privacy Policy

### LINKED ISSUE #938: Update, add 'Reviewed on' date to Privacy Policy
In the [Privacy Policy](https://scratch.mit.edu/privacy_policy/):

- Update the link to the "Scratch Foundation" from codetolearn.org to http://www.scratchfoundation.org/

- Add a line at the bottom of the [Privacy Policy page](https://scratch.mit.edu/privacy_policy/) (a la [Terms of Use](https://scratch.mit.edu/terms_of_use/) page): **The Scratch Privacy Policy was last updated: October 2016**

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #938 

Test cases:
- Link to the Scratch Foundation should now be http://www.scratchfoundation.org/ instead of http://codetolearn.org
- There should now be a line at the bottom of the page that reads: "The Scratch Privacy Policy was last updated: October 2016" (Text should also be **unbolded**)

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor @thisandagain @rschamp

File: src/views/privacypolicy/privacypolicy.jsx [hunk 1]
```diff
@@ -203,6 +203,7 @@ var Privacypolicy = React.createClass({
                              Policy on a regular basis.
                         </p>
                     </section>
+                    <p><b>The Scratch Privacy Policy was last updated: October 2016</b></p>
```
Comment (mewtaylor) [inline src/views/privacypolicy/privacypolicy.jsx]: @kaschm is this supposed to be emboldened text in the page too, or was it just bold in the issue you created to make it distinct?

**Comment by kaschm** [comment]
bold is good :+1: thanks!

File: src/views/privacypolicy/privacypolicy.jsx (hunk 1 above)
Comment (kaschm) [inline src/views/privacypolicy/privacypolicy.jsx]: @mewtaylor @TheGrits bold is good thanks :+1:

Comment (TheGrits) [inline src/views/privacypolicy/privacypolicy.jsx]: @kaschm Should the similar text on the Terms of Use be bolded as well?

Comment (kaschm) [inline src/views/privacypolicy/privacypolicy.jsx]: @TheGrits my bad - I thought the text on the Terms of Use was bolded :( Can you unbold this text to make it consistent with that page? Sorry for the back and forth.

Comment (TheGrits) [inline src/views/privacypolicy/privacypolicy.jsx]: @kaschm No worries, I'll do it right now.
