### PR TITLE
Fix gh-959: Localize Credits Page

### LINKED ISSUE #959: Should credits page be translated?
**The Credits page**
https://scratch.mit.edu/info/credits/

screen shot 2016-09-20 at 11 38 52 am

Currently it is untranslated, and the strings are not part of the pootle database. Should it be translated?

### PR DESCRIPTION
**Pull request by TheGrits**
Should at least significantly fix #959 
I did not change any of the strings for translation purposes, but I did make one text change for grammar. (As explained in the test cases)

Test cases:
-

- Check that the page loads English correctly (translated strings aren't likely)
- Check that all the links work
> National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, MacArthur Foundation.

should now read 
> National Science Foundation, Scratch Foundation, Google, LEGO Foundation, Intel, Cartoon Network, Lemann Foundation, and the MacArthur Foundation.

I'm hoping there aren't any little typos/gotchas hiding from me, but they could still be there.

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor @rschamp @thisandagain (and @chrisgarrity as issue owner)

File: src/views/credits/credits.jsx [hunk 1]
```diff
@@ -185,125 +187,29 @@ var Credits = React.createClass({
...
-                <p>
-                    The ideas of Seymour Papert and Alan Kay have deeply inspired and influenced our work on Scratch.
-                </p>
-
-                <h2>Supporting Organizations</h2>
-                <p>
-                    The following organizations have provided major financial support for Scratch:
-                </p>
-                <p>
-                    <a href="http://www.nsf.gov/">National Science Foundation</a>,
```
Comment (mewtaylor) [inline src/views/credits/credits.jsx]: For all of these links with organizations, we don't want to add them to the `intl.json` file – they're proper nouns, so I think we want to keep them untranslated

Comment (TheGrits) [inline src/views/credits/credits.jsx]: @mewtaylor 👍 Sounds good, I'll fix that right away!

**Comment by TheGrits** [comment]
@mewtaylor Done!

File: src/views/credits/credits.jsx [hunk 2]
```diff
@@ -10,9 +12,9 @@ var Credits = React.createClass({
     render: function () {
         return (
             <div className="inner credits">
-                <h1>Scratch Credits and Contributors</h1>
-                <h2>MIT Scratch Team</h2>
```
Comment (mewtaylor) [inline src/views/credits/credits.jsx]: One more here to remove from the json, since `MIT Scratch Team` is a proper noun :)

File: src/views/credits/credits.jsx [hunk 3]
```diff
@@ -185,64 +187,22 @@ var Credits = React.createClass({
...
-                    <a href="http://www.nsf.gov/awardsearch/showAward?AWD_ID=0325828"> initial NSF Scratch grant</a>
-                    ) at the University of Pennsylvania Graduate School of Education, Karen Brennan (who leads the
-                    <a href="http://scratched.gse.harvard.edu/"> ScratchEd project</a>) at the Harvard Graduate School
-                    of Education, Benjamin Mako Hill at the University of Washington, Andrés Monroy Hernández at
-                    Microsoft Research, Mimi Ito and Crystle Martin at the University of California, Irvine, Quinn
-                    Burke at College of Charleston, Deborah Fields at Utah State University, and Kylie Peppler at
-                    Indiana University.
-                </p>
+                <h2><FormattedMessage id='credits.partnersTitle' /></h2>
+                <p><FormattedMessage id='credits.partnersBody' /></p>
```
Comment (mewtaylor) [inline src/views/credits/credits.jsx]: I think this needs to be `FormattedHTMLMessage` if it has links in it

Comment (TheGrits) [inline src/views/credits/credits.jsx]: I don't think it has links in it? https://github.com/LLK/scratch-www/pull/1148/files#diff-5f47088cec7083daba3b48c14ae030e4R9

**Comment by TheGrits** [comment]
@mewtaylor Back to you! :)

File: src/views/credits/credits.jsx (hunk 3 above)
Comment (mewtaylor) [inline src/views/credits/credits.jsx]: `partnersBody` appears to, right?

Comment (mewtaylor) [inline src/views/credits/credits.jsx]: Whoops nvm – confused this with `researchersBody` 👍

Comment (TheGrits) [inline src/views/credits/credits.jsx]: Nope, `partnersBody` doesn't have any links. (Matching production: 
screenshot 2017-02-14 at 2 04 02 pm)

Comment (TheGrits) [inline src/views/credits/credits.jsx]: @mewtaylor lol looks like you ninja-ed me again.

**Comment by TheGrits** [comment]
@mewtaylor No problem, any time. 👍
