### PR TITLE
Fix gh-1634: Fix Localization on Developers Page

### LINKED ISSUE #1634: Strings not marked for translation
The `Projects` header on the Developers page:
https://github.com/LLK/scratch-www/blob/18f82fce3ffecd366168740ed827392eb88a66cc/src/views/developers/developers.jsx#L67

The paragraph about ScratchJr:
https://github.com/LLK/scratch-www/blob/18f82fce3ffecd366168740ed827392eb88a66cc/src/views/developers/developers.jsx#L97

### PR DESCRIPTION
**Pull request by TheGrits**
Resolves #1634 

## Test cases
- "Projects" should now be localized
- "ScratchJr" should now be localized
- The text body for ScratchJr should now be localized

### CODE REVIEW

**Comment by TheGrits** [comment]
@chrisgarrity

File: src/views/developers/developers.jsx [hunk 1]
```diff
@@ -92,15 +92,9 @@ var Developers = React.createClass({
                         </FlexRow>
                         <FlexRow className="sidebar-row">
                             <div className="body-copy column">
-                                <h3>ScratchJr</h3>
+                                <h3><FormattedMessage id='developers.jrTitle' /></h3>
```
Comment (chrisgarrity) [inline src/views/developers/developers.jsx]: Actually, we ask translators not to translate 'Scratch' or 'ScratchJr' since they're names. Since there's no text other than ScratchJr this one doesn't need translation.

File: src/views/developers/l10n.json [hunk 2]
```diff
@@ -14,6 +14,8 @@
   "developers.wwwTitle": "Scratch WWW",
   "developers.wwwIntro": "Scratch-www is a standalone web client for the Scratch Community, built using React and Redux. Access the code and documentation through Github <a href=\"https://github.com/LLK/scratch-www\">here</a>.",
   "developers.principlesIntro": "We created Scratch to empower young people to think creatively, reason systematically, and work collaboratively. We are guided by a set of <b>Learning Principles</b> and <b>Design Principles</b> that we hope you will follow as you develop new tools and technologies with Scratch Blocks.",
+  "developers.jrTitle": "ScratchJr",
+  "developers.jrBody": "ScratchJr is an introductory programming language that enables young children (ages 5-7) to create their own interactive stories and games. For more information, visit the <a href=\"https://www.scratchjr.org/\">ScratchJr website</a> or access the code and documentation <a href=\"https://github.com/LLK/scratchjr\">here</a>.",
```
Comment (chrisgarrity) [inline src/views/developers/l10n.json]: As long as we're making changes, let's change 'here' to 'on GitHub'. In general, we should try to make sure it's clear when clicking a link will take you off the Scratch site.

Comment (VutonDesign) [reply src/views/developers/l10n.json]: I agree with this, I think I actually suggested it a while ago. 👍

Comment (chrisgarrity) [reply src/views/developers/l10n.json]: Yes, I hadn't realized at that point that the text wasn't translated, so it would have been fine to change the wording. Thanks for pointing it out!

**Comment by TheGrits** [comment]
@chrisgarrity Sounds good to me! I hope to get these changes made on Wednesday.

**Comment by TheGrits** [comment]
@chrisgarrity That should do the trick!

**Comment by chrisgarrity** [comment]
@TheGrits Looks good. We're in the middle of testing the next deploy, so I may not merge until after the deploy.

**Comment by TheGrits** [comment]
@chrisgarrity I'm in no hurry. :)
