### PR TITLE
Fix GH-123: Shuffle top loved and top remixed

### LINKED ISSUE #123: What the Community is Loving row not randomized
The order of projects in the top loved row of the home page is not randomized - the projects always appear in the same order

### PR DESCRIPTION
**Pull request by technoboy10**
This PR resolves #123 by using a Fisher-Yates shuffle<sup>1</sup> on the array of projects in the top loved and top remixed section.

[1] Source: https://www.frankmitchell.org/2015/01/fisher-yates/

### CODE REVIEW

File: src/views/splash/splash.jsx [hunk 1]
```diff
@@ -110,6 +110,23 @@ var Splash = injectIntl(React.createClass({
...
+        }
+
+        for (i = arr.length - 1; i > 0; i -= 1) {
+            j = Math.floor(Math.random() * (i + 1));
+            temp = tempArray[i];
+            tempArray[i] = tempArray[j];
+            tempArray[j] = temp;
+        }
+        return tempArray;
+    },
```
Comment (rschamp) [inline src/views/splash/splash.jsx]: Would you please move this to a utility module in lib?

**Comment by rschamp** [comment]
This looks good! Just one nit.

File: src/views/splash/splash.jsx (hunk 1 above)
Comment (technoboy10) [inline src/views/splash/splash.jsx]: Done!
