### PR TITLE
Fix GH-749: Fix formatting for a few form elements

### LINKED ISSUE #749: Validation messages are not aligned with inputs on teacher/student registration

### PR DESCRIPTION
**Pull request by mewtaylor**
and make use of the FRC `elementWrapperClassName`, since they way we did it before – custom `className` strings on the element – was not working. Fixes #749 .

### Elements to test ###
* Phone number input
* "Why use scratch" textarea
* Checkbox group

### CODE REVIEW

File: src/components/forms/checkbox.jsx [hunk 1]
```diff
@@ -15,9 +15,7 @@ var Checkbox = React.createClass({
             this.props.className
         );
         return (
-            <div className={classes}>
-                <FRCCheckbox {... this.props} />
-            </div>
+            <FRCCheckbox elementWrapperClassName={classes} {... this.props} />
```
Comment (rschamp) [inline src/components/forms/checkbox.jsx]: Why did you decide to move the class to an internal part of the component?  I would expect the `className` I give to a component to be applied to the outermost element of that component so that I can target anything within the component under that `className`, e.g.
```jsx
<Checkbox className="my-unique-checkbox" />
```
```scss
.my-unique-checkbox {
    // Styles for the outermost element
    .help-block { // Or some other sibling to the element wrapper
        // ...
    }
}
```

Most importantly doing it this way makes it so you don't have to know how the checkbox component works in order to add outermost block-level styles to it (`float`, etc.). Currently, wouldn't you need to add styles to the row classname, and then it wouldn't be namespaced to the className you gave to your component?

Comment (mewtaylor) [inline src/components/forms/checkbox.jsx]: I did it this way so that the stylings could be uniformly applied to elements inside of `.form-group` elements. The way FRC works, it builds a `Row` around everything, so I was seeing this more the outermost wrapper around the element itself, even if it wasn't outside of `Row`. It made more sense for me for it to be `.form-group > .[element]` rather than `.[element] > .form-group`.

The other reason is because this is the only place we do this – I added that wrapper in the initial commit of this feature because applying `className` directly onto `FRCCheckbox` wasn't working. We had this set up, applying `className` to FRC elements to provide custom formatting, everywhere. However, I discovered in this bug that FRC was basically ignoring all of those classnames, and not applying them, since that's not how it works. 

When I learned how `elementWrapperClassName` worked, it seemed to make more sense to me to use that, rather than adding another `div` wrapper around all FRC components to make this uniform.

Comment (rschamp) [inline src/components/forms/checkbox.jsx]: I don't agree that we want `.form-group > .[element]` (I think it's better to think `.form-group > .[component]`) since that's inverted in terms of scoping. It makes a particular component's `.form-group` inaccessible without affecting _all_ `.form-group`s. How would you put a border around one checkbox's row, but not all of them on the page?

I agree with getting rid of the `<div></div>` wrapper, but I think you want the `className` to become the `rowClassName` not the `elementWrapperClassName`.

File: src/components/forms/phone-input.jsx [hunk 2]
```diff
@@ -53,9 +53,9 @@ var PhoneInput = React.createClass({
                                      label={null}
                                      disabled={this.isFormDisabled() || this.props.disabled}
                     />
+                    {this.renderErrorMessage()}
                 </div>
                 {this.renderHelp()}
```
Comment (rschamp) [inline src/components/forms/phone-input.jsx]: I was wrong about this being outside the row on the others: https://github.com/twisty/formsy-react-components/blob/master/src/input.js#L92 https://github.com/twisty/formsy-react-components/blob/master/src/textarea.js#L59

Comment (mewtaylor) [inline src/components/forms/phone-input.jsx]: Cool – I'll move it in!

File: src/components/forms/textarea.jsx [hunk 3]
```diff
@@ -17,7 +17,7 @@ var TextArea = React.createClass({
         return (
             <FRCTextarea {... this.props}
                          className={classes}
-                         elementWrapperClassName="textarea-group" />
+                         rowClassName="textarea-row" />
```
Comment (rschamp) [inline src/components/forms/textarea.jsx]: Shouldn't this get classes?

Comment (mewtaylor) [inline src/components/forms/textarea.jsx]: not the way it was originally set up – `.textarea` is applied to style the `textarea` element itself, rather than wrappers, since it need to override defaults. We could switch it so that custom styling applies to the wrapping row, if we want to. I'd be fine with that.

Comment (rschamp) [inline src/components/forms/textarea.jsx]: If you would, could you update the styles for all of the input components so it works in the way we want, where the `className` is applied to the top-level element?  It looks like even `Input` ignores `className` right now.

Comment (rschamp) [inline src/components/forms/textarea.jsx]: Oh nvm, I was looking at something outdated

Comment (mewtaylor) [inline src/components/forms/textarea.jsx]: I think you're still right about `Input` – must've missed that when I was doing the others, I'll do that now

Comment (rschamp) [inline src/components/forms/textarea.jsx]: Thanks!

**Comment by rschamp** [comment]
@mewtaylor While you're working on it, just found this one:
image

**Comment by mewtaylor** [comment]
@rschamp already fixed

File: src/components/registration/steps.jsx [hunk 4]
```diff
@@ -315,6 +315,7 @@ module.exports = {
                             <div className="gender-input">
                                 <Input name="user.genderOther"
                                        type="text"
+                                       className="no-label"
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: Rather than needing to know about this class, could `Input` just give the class to itself if there is no `label` prop?

**Comment by thisandagain** [comment]
@mewtaylor PR failing CI due to trailing spaces.
