### PR TITLE
Fix gh-924: Localize Developers Page

### LINKED ISSUE #924: Should the Developers page be translated?
Chrome Version 53.0.2785.116 (64-bit), Mac OS X El Capitan 10.11.6 (15G1004)

https://scratch.mit.edu/developers

@chrisgarrity and I were wondering about this when we were looking at https://github.com/LLK/scratchr2/issues/4066. Currently, the Developers page remains in English when you choose a 100% translated language like Italian. We weren't sure if perhaps it remained untranslated intentionally since we may only really be able to work with Developers comfortable communicating in English?

### PR DESCRIPTION
**Pull request by TheGrits**
Should (at least start to) fix #924 (as per https://github.com/LLK/scratch-www/issues/924#issuecomment-251434374 )

Changes made:
- Added localized English version to the `l10n.json` file
- Remove hard-coded English text from `developers.jsx`
- Add `FormattedMessage` and `FormattedHTMLMessage` requirements to `developers.jsx`

Test cases:
- Check that all text is appearing the same as production, including links

### CODE REVIEW

**Comment by TheGrits** [comment]
@mewtaylor @thisandagain @rschamp (And @kaschm because you were the one who said to localize the page)

File: src/views/developers/developers.jsx [hunk 1]
```diff
@@ -15,38 +18,36 @@ var Developers = React.createClass({
             <div className="developers">
                 <TitleBanner className="masthead">
                     <div className="inner">
-                        <h1>Scratch for Developers</h1>
+                        <h1><FormattedMessage id='developers.title' /></h1>
                         <p className="intro">
-                            On this page, you’ll find information about open source projects created and maintained{' '}
-                            by the <a href="https://scratch.mit.edu/info/credits">Scratch Team at MIT</a>, as well{' '}
-                            as our thoughts on best practices for designing learning experiences for children.
+                            <FormattedMessage id='developers.intro' />
```
Comment (mewtaylor) [inline src/views/developers/developers.jsx]: This looks like it might need to be `FormattedHTMLMessage`

File: src/views/developers/developers.jsx [hunk 2]
```diff
@@ -101,72 +87,54 @@ var Developers = React.createClass({
...
                     <section id="principles">
                         <span className="nav-spacer"></span>
-                        <h2>Principles</h2>
+                        <h2><FormattedMessage id='developers.principlesTitle' /></h2>
                         <p className="intro">
-                            We created Scratch to empower young people to think creatively, reason systematically,{' '}
-                            and work collaboratively. We are guided by a set of <b>Learning Principles</b> and{' '}
-                            <b>Design Principles</b> that we hope you will follow as you develop new tools and{' '}
-                            technologies with Scratch Blocks.
+                            <FormattedMessage id='developers.principlesIntro' />
```
Comment (mewtaylor) [inline src/views/developers/developers.jsx]: the `<b>` tags suggest this needs to be `FormattedHTMLMessage` I believe.

File: src/views/developers/developers.jsx [hunk 3]
```diff
@@ -101,72 +87,54 @@ var Developers = React.createClass({
...
                             </div>
                         </FlexRow>
 
                         <FlexRow className="sidebar-row">
                             <div className="body-copy column">
-                                <h3>Design Principles</h3>
+                                <h3><FormattedMessage id='developers.designPrinciplesTitle' /></h3>
                                 <dl>
-                                    <dt>Low Floor & Wide Walls</dt>
+                                    <dt><FormattedMessage id='developers.designPrinciplesRoomTitle' /></dt>
```
Comment (mewtaylor) [inline src/views/developers/developers.jsx]: `Room` – Nice choice of naming :)

File: src/views/developers/developers.jsx (hunk 2 above)
Comment (TheGrits) [inline src/views/developers/developers.jsx]: @mewtaylor Yep. Once again, good catch!

File: src/views/developers/developers.jsx (hunk 3 above)
Comment (TheGrits) [inline src/views/developers/developers.jsx]: @mewtaylor Haha, thanks.

**Comment by TheGrits** [comment]
@mewtaylor Should be ready to roll now, thanks!
