### PR TITLE
Fix gh-3781: Delay Scratch Conference

### LINKED ISSUE #3781: Update Scratch conference page to announce one year delay
We need the text updated on the Scratch Conference page http://scratch.mit.edu/conference to explain that the conference is delayed one year until July 2021. I will post updated text below, but am posting this issue now to put it on the radar for scheduling. 

(We will also be sending out an email announcement and updating the Eventbrite page this week April 2 or 3.)

### PR DESCRIPTION
**Pull request by Accio1**
### Resolves:

This resolves #3781 

### Changes:

The Scratch Conference was delayed to 2021, so this pull request changes the Scratch Conference page in order to reflect the changes made to the dates of the Scratch Conference.

### Test Coverage:

I didn't really understand how to test this, and when I tried to test it, it wouldn't work, so instead, I re-read the changes that I made twice in order to try and catch anything that I might have broken.

### CODE REVIEW

File: src/views/conference/2020/index/index.jsx [hunk 1]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
                     <br />
                     <br />
                     <FormattedMessage id="conference-2020.registrationDelayed" />
+                    <br />
+                    <FormattedMessage
```
Comment (apple502j) [inline src/views/conference/2020/index/index.jsx:95]: Trailing space:
```suggestion
                    <FormattedMessage
```

File: src/views/conference/2020/index/index.jsx [hunk 2]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
                     <br />
                     <br />
                     <FormattedMessage id="conference-2020.registrationDelayed" />
+                    <br />
+                    <FormattedMessage 
+                        id="conference-2020.connectNow"
+                        values={{
+                           scratchInPracticeLink: <a href="https://sip.scratch.mit.edu/">
```
Comment (apple502j) [inline src/views/conference/2020/index/index.jsx:98]: indent
```suggestion
                            scratchInPracticeLink: <a href="https://sip.scratch.mit.edu/">
```

File: src/views/conference/2020/index/index.jsx [hunk 3]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
...
+                                <FormattedMessage id="conference-2020.scratchInPracticeText" />
```
Comment (apple502j) [inline src/views/conference/2020/index/index.jsx:99]: indent
```suggestion
                                 <FormattedMessage id="conference-2020.scratchInPracticeText" />
```

File: src/views/conference/2020/index/index.jsx [hunk 4]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
...
+                            </a>
```
Comment (apple502j) [inline src/views/conference/2020/index/index.jsx:100]: indent + trailing space
```suggestion
                           </a>
```

File: src/views/conference/2020/index/index.jsx [hunk 5]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
...
                     <br />
                     <FormattedMessage id="conference-2020.registrationDelayed" />
+                    <br />
+                    <FormattedMessage 
+                        id="conference-2020.connectNow"
+                        values={{
+                           scratchInPracticeLink: <a href="https://sip.scratch.mit.edu/">
+                                <FormattedMessage id="conference-2020.scratchInPracticeText" />
+                            </a> 
+                        }}
```
Comment (apple502j) [inline src/views/conference/2020/index/index.jsx:101]: trailing space
```suggestion
                        }}
```

File: src/views/conference/2020/index/l10n.json [hunk 6]
```diff
@@ -1,26 +1,26 @@
...
 
     "conference-2020.registrationTitle": "Registration:",
     "conference-2020.registrationFee": "Conference Fee: $250",
     "conference-2020.registrationOpen": "The conference fee includes 7 meals (3 breakfast, 3 lunches, 1 dinner) plus refreshments during the day.",
-    "conference-2020.registrationDelayed": "We have delayed the opening of registration until April 3. We’re excited to gather together as a community in July, but we are closely monitoring the situation around the Coronavirus (COVID-19) to determine how it might impact our plans. We will provide more information as it becomes available.",
+    "conference-2020.registrationDelayed": "In response to the coronavirus crisis (COVID-19), we have decided to delay the Scratch conference for one year, to July 22-24, 2021. We are sending well wishes to our entire global community and hope you can join us then!",
+    "conference-2020.connectNow": "Want to connect now? We invite you to learn more about our online conversations, resources, and events at {scratchInPracticeLink}.",
+    "conference-2020.scratchInPracticeText": "Scratch In Practice",
```
Comment (apple502j) [inline src/views/conference/2020/index/l10n.json:20]: i is lowercase
```suggestion
    "conference-2020.scratchInPracticeText": "Scratch in Practice",
```

File: src/views/conference/2020/index/l10n.json [hunk 7]
```diff
@@ -1,26 +1,26 @@
...
+    "conference-2020.dateDesc": "July 22-24, 2021 | Cambridge, MA, USA",
+    "conference-2020.dateDescMore": " (with opening reception the evening of July 21)",
     "conference-2020.locationDetails": "MIT Media Lab, Cambridge, MA",
-    "conference-2020.seeBelow": "Learn more about conference dates and locations below.",
 
     "conference-2020.date": "When:",
     "conference-2020.location": "Where:",
 
-    "conference-2020.desc1": "Join us for the Scratch Conference, an international gathering where educators, researchers, and developers share ideas for supporting creative learning with Scratch.",
+    "conference-2020.desc1": "Join us for the Scratch Conference, an international gathering where educators, researchers, and developers share ideas for supporting creative learning with Scratch. Due to the global health crisis, we have delayed the conference for one year, to July 22-24, 2021.",
```
Comment (rschamp) [inline src/views/conference/2020/index/l10n.json:11]: I think the added text should be its own string so that we can easily bold it, and so that this string does not need to be retranslated:
```suggestion
    "conference-2020.desc1": "Join us for the Scratch Conference, an international gathering where educators, researchers, and developers share ideas for supporting creative learning with Scratch.",
    "conference-2020.desc1a": "Due to the global health crisis, we have delayed the conference for one year, to July 22-24, 2021.",
```

In addition to this, please add this new string to the page (at https://github.com/LLK/scratch-www/pull/3801/files#diff-63ab2bce5ecdcc31263acf95d31f7c58L31):
```jsx
                    <FormattedMessage id="conference-2020.desc1" />
                    <strong><FormattedMessage id="conference-2020.desc1a" /></strong>
```

File: src/views/conference/2020/index/index.jsx [hunk 8]
```diff
@@ -91,6 +91,15 @@ const ConferenceSplash = () => (
                     <br />
                     <br />
                     <FormattedMessage id="conference-2020.registrationDelayed" />
+                    <br />
```
Comment (rschamp) [inline src/views/conference/2020/index/index.jsx:94]: Please add another linebreak here:
```suggestion
                    <br />
                    <br />
```

File: src/views/conference/2020/index/l10n.json (hunk 7 above)
Comment (Accio1) [reply src/views/conference/2020/index/l10n.json:11]: Shouldn't there be a space either at the end of desc1 or at the start of desc1a so that it doesn't just look like this:

"...supporting creative learning with Scratch.Due to the global health crisis..."

**Comment by Accio1** [comment]
I just made the tweaks. I also added a space at the start of desc1a so that the two sentences wouldn't be stuck together when they're displayed.

File: src/views/conference/2020/index/l10n.json [hunk 9]
```diff
@@ -1,26 +1,27 @@
...
+    "conference-2020.dateDesc": "July 22-24, 2021 | Cambridge, MA, USA",
+    "conference-2020.dateDescMore": " (with opening reception the evening of July 21)",
     "conference-2020.locationDetails": "MIT Media Lab, Cambridge, MA",
-    "conference-2020.seeBelow": "Learn more about conference dates and locations below.",
 
     "conference-2020.date": "When:",
     "conference-2020.location": "Where:",
 
     "conference-2020.desc1": "Join us for the Scratch Conference, an international gathering where educators, researchers, and developers share ideas for supporting creative learning with Scratch.",
+    "conference-2020.desc1a": " Due to the global health crisis, we have delayed the conference for one year, to July 22-24, 2021.",
```
Comment (rschamp) [inline src/views/conference/2020/index/l10n.json:12]:
```suggestion
    "conference-2020.desc1a": "Due to the global health crisis, we have delayed the conference for one year, to July 22-24, 2021.",
```

**Comment by Accio1** [comment]
> Thank you!
> 
> Frequently translators will remove leading/trailing spaces like this, so I moved it to be be an explicit space between the `FormattedMessage`s.

Thanks! I hadn't realised that's what usually happens. Now I'll know for next time!
