### PR TITLE
Fix GH-850 // Add image links

### LINKED ISSUE #850: make resource icons clickable on Educators page
I wonder if the icons could be clickable to get to each of the three resources on the Educators page:
image

### PR DESCRIPTION
**Pull request by St19Galla**
This PR fixes #850 by changing the images to be clickable. 

@mewtaylor

### CODE REVIEW

File: src/views/teachers/landing/landing.jsx [hunk 1]
```diff
@@ -82,19 +82,25 @@ var Landing = injectIntl(React.createClass({
                         <h3 id="guides-header"><FormattedMessage id="teacherlanding.guidesTitle" /></h3>
                         <FlexRow className="guides-and-tutorials">
                             <div>
-                                <img src="/svgs/teachers/resources.svg" alt="resources icon" />
+                                <a href="https://scratch.mit.edu/help/">
```
Comment (mewtaylor) [inline src/views/teachers/landing/landing.jsx]: I think this can be a relative url, like it is in https://github.com/LLK/scratch-www/blob/develop/src/views/teachers/landing/l10n.json#L17

File: src/views/teachers/landing/landing.jsx [hunk 2]
```diff
@@ -82,19 +82,25 @@ var Landing = injectIntl(React.createClass({
...
+                                    <img src="/svgs/teachers/resources.svg" alt="resources icon" />
+                                </a>
                                 <p>
                                     <FormattedHTMLMessage id="teacherlanding.helpPage" />
                                 </p>
                             </div>
                             <div>
-                                <img src="/svgs/teachers/tips-window.svg" alt="tips window icon" />
+                                <a href="https://scratch.mit.edu/projects/editor/?tip_bar=home">
```
Comment (mewtaylor) [inline src/views/teachers/landing/landing.jsx]: same with this one https://github.com/LLK/scratch-www/blob/develop/src/views/teachers/landing/l10n.json#L18

**Comment by mewtaylor** [comment]
@St19Galla just a couple minor things, then this should be ready to go!

**Comment by St19Galla** [comment]
whoops, fixing the error now, I see what I did :P

**Comment by mewtaylor** [comment]
@St19Galla looks good, thanks!

**Comment by mewtaylor** [comment]
tested on staging, Mac OSX 10.11, FF and Chrome. Links work correctly for all three images.

/cc @jwzimmer
