### PR TITLE
Fix GH-872: Check for username before sending

### LINKED ISSUE #872: "Oops something went wrong" error with blank username field - Teacher Registration
**Staging**

If you fill out the fields after getting this error, you can continue to the next page, and it doesn't seem to cause an error at the end of registration.

**Safari Version 9.1.2 (11601.7.7), Mac OS X El Capitan**
- Just from typing in a few known usernames to test out the validation (I didn't click next, just clicked in between username and password fields, I got this error:
  (404 error)
  (URL in the error was https://[staging]/accounts/check_username//)

screen shot 2016-08-22 at 5 57 02 pm
- Repro'd by trying different names, typing in password field, going back and forth between the two fields (did not click Next):

screen shot 2016-08-22 at 6 08 25 pm
screen shot 2016-08-22 at 6 08 16 pm

In Safari on Mac (see comment above), I'm still seeing this error after clearing cache and history. I see it in **Chrome 52**, too. The repro steps are: go to `educators/register`, click Next, put your cursor in username field, click Next again.
screen shot 2016-08-23 at 1 30 44 pm

### PR DESCRIPTION
**Pull request by mewtaylor**
the `//` for an empty username that gets sent to the backend causes a 500 error. This is an edge case in formsy, as it has not detected a change value yet, so handle it in the username validation method. Fixes #872

### CODE REVIEW

File: src/components/registration/steps.jsx [hunk 1]
```diff
@@ -91,6 +91,13 @@ module.exports = {
         },
         validateUsername: function (username, callback) {
             callback = callback || function () {};
+            if (username.length < 1) {
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: `if (!username)` might be safer since it would cover null/undefined too (and would avoid a possible "Cannot read property 'length' of undefined" error).

Comment (mewtaylor) [inline src/components/registration/steps.jsx]: Ah – I thought that `Input` would be handling that by sending an empty string but sounds good.

**Comment by rschamp** [comment]
We should probably also avoid that 500 in the check username view on scratchr2. But that's not a big deal really.
