### PR TITLE
Fix GH-933: Put label for “Not Required” above input

### LINKED ISSUE #933: Match text format/ location for "Not Required" on different steps of Teacher Registration
Staging, Safari Version 9.1.3 (11601.7.8), Mac OS X El Capitan

From https://github.com/LLK/scratch-www/pull/896:

We added "Not Required" by the Zip Code field since we stopped requiring Zip Codes for non-USA countries. We added it in a different location/ format than we did on other steps (e.g. Website field). We should be consistent.

screen shot 2016-09-30 at 2 05 54 pm
screen shot 2016-09-30 at 2 04 54 pm

/cc @carljbowman

### PR DESCRIPTION
**Pull request by mewtaylor**
Fixes #933 by giving the "Not Required" styling used in organization url (i.e. separated out label elements)

/cc @rschamp

### CODE REVIEW

File: src/components/registration/steps.jsx [hunk 1]
```diff
@@ -752,7 +759,7 @@ module.exports = {
                                            id: 'registration.validationMaxLength'
                                        })
                                    }}
-                                   required={(this.state.countryChoice === 'us')} />
+                                   required={(this.state.countryChoice === 'us') ? true : 'isFalse'} />
```
Comment (rschamp) [inline src/components/registration/steps.jsx]: https://github.com/LLK/scratch-www/blob/develop/src/components/forms/input-hoc.jsx#L14 the "not required" help text is added automatically if the field isn't required. Why is the required state set to `'isFalse'` rather than just `false`?

Comment (rschamp) [inline src/components/registration/steps.jsx]: Er, I guess the real question is why is that broken, requiring you to use `isFalse`?
