### PR TITLE
Fix GH-930: Update wedo2 text for new Windows deploy

### LINKED ISSUE #930: Update wedo page to include Windows 10
scratch.mit.edu/wedo should now include language around compatibility with Win 10: 

The LEGO WeDo 2.0 extension is currently only available for Mac OSX. We plan to release a Windows version later in 2016.

update to:

The LEGO WeDo 2.0 extension is available for Mac OSX and Windows 10+

also update the download text and link:

1. Install Device Manager

The Device Manager lets you connect WeDo 2.0 to Scratch using Bluetooth 

**Download for Mac OSX** [existing link]
**Download for Win 10+** [needs link @cwillisf ]

### PR DESCRIPTION
**Pull request by mewtaylor**
Fixes #930 by updating the text – this is still in progress, as a Windows device manager link is still needed.

### CODE REVIEW

File: src/views/wedo2/wedo2.jsx [hunk 1]
```diff
@@ -44,6 +44,14 @@ var Wedo2 = React.createClass({
                                 </h4>
                                 <p>
                                     <FormattedHTMLMessage id='wedo2.installText' />
+                                    <br />
+                                    <a href="https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1084869222&mt=12">
+                                        <FormattedMessage id='wedo2.downloadMac' />
+                                    </a>
+                                    <br />
+                                    <a href="/">
```
Comment (chrisgarrity) [inline src/views/wedo2/wedo2.jsx]: Should this be a link to the Device Manager setup on downloads.scratch.mit.edu? e.g:
http://downloads.scratch.mit.edu/device-manager/Scratch%20Device%20Manager%20Setup%201.1.0.exe

Comment (mewtaylor) [inline src/views/wedo2/wedo2.jsx]: I think we're waiting for a new link from @cwillisf, not sure if that's the intended one or not

File: src/views/wedo2/wedo2.jsx [hunk 2]
```diff
@@ -44,6 +44,14 @@ var Wedo2 = React.createClass({
                                 </h4>
                                 <p>
                                     <FormattedHTMLMessage id='wedo2.installText' />
+                                    <br />
+                                    <a href="https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1084869222&mt=12">
```
Comment (mewtaylor) [inline src/views/wedo2/wedo2.jsx]: @rschamp looks like the linter is failing on this again – I assume I should get a bitly link for now, since we still need to add in the global linting rules for www?

Comment (rschamp) [inline src/views/wedo2/wedo2.jsx]: Oh, yeah, it was actually missing from eslint-config-scratch until last week too https://github.com/LLK/eslint-config-scratch/pull/8. What about adjusting the local lint config?

File: src/views/wedo2/wedo2.jsx (hunk 1 above)
Comment (cwillisf) [inline src/views/wedo2/wedo2.jsx]: New link: https://downloads.scratch.mit.edu/device-manager/ScratchDeviceManager-1.1.0.exe
It's still not the final file but I think we can treat that as the final link.

File: src/views/wedo2/wedo2.jsx (hunk 2 above)
Comment (mewtaylor) [inline src/views/wedo2/wedo2.jsx]: 👍 was wondering if we wanted to leave it untouched until using the config, but sounds good to me!

**Comment by mewtaylor** [comment]
@kaschm assigned to you for content confirmation, thanks!

**Comment by kaschm** [comment]
:+1: lgtm thanks @mewtaylor
