### PR TITLE
Fix GH-543: Add teacher banner to splash page

### LINKED ISSUE #543: Persistent homepage element for Teacher Accounts
Show persistent homepage element in all logged in Teacher Accounts. 

@carljbowman for more details and designs

### PR DESCRIPTION
**Pull request by mewtaylor**
This only shows if the logged in user is a teacher, and persists for teachers. Fixes #543.

### Test Cases ###
https://github.com/LLK/scratch-www/wiki/Testing-Scratch-www#Teacher_Banner

### CODE REVIEW

File: src/lib/jar.js [hunk 1]
```diff
@@ -73,6 +73,21 @@ var Jar = {
         var expires = '; expires=' + new Date(new Date().setYear(new Date().getFullYear() + 1)).toUTCString();
         var path = '; path=/';
         document.cookie = obj + expires + path;
+    },
+    getSignedValue: function (cookieName, signedValue, callback) {
```
Comment (rschamp) [inline src/lib/jar.js]: The naming here is counterintuitive: `getSignedValue` gets the *un*signed value associated with the key named `signedValue`?

Comment (mewtaylor) [inline src/lib/jar.js]: hmm. yeah I see that. I was going with the name based on the fact that it is unsigning as part of its process, so as to suggest that it's getting what wan an originally signed value, but I see how that might be confusing...

Comment (mewtaylor) [inline src/lib/jar.js]: `getValueFromSigned`?

Comment (rschamp) [inline src/lib/jar.js]: Maybe `getAndUnsign` or just `getUnsignedValue` since `get` already implies it's just going to return the value as-is?  I think for consistency `signedValue` should become `name` like in the other methods.

Comment (rschamp) [inline src/lib/jar.js]: I also wonder if the signing stuff should move into another module since it doesn't really have to do with cookies, it just happens that cookies are signed.

**Comment by rschamp** [comment]
Another way to do this would be to consolidate permissions and token into one `sessionCookie` reducer that would know when it was decompressed/unsigned so we could just do it one time. But I think I like it this way where it's divided on conceptual boundaries, and the unsigning/decompressing is probably negligible in terms of performance. It's something to keep an eye on though.

File: src/components/teacher-banner/teacher-banner.jsx [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+            this.props.className
+        );
+        return (
+            <TitleBanner className={classes}>
+                <FlexRow className="inner">
+                    <div className="welcome">
+                        {this.props.session.status === sessionActions.Status.FETCHED ? (
+                            this.props.session.session.user ? [
+                                <h3>
+                                    {this.props.messages['teacher-banner.greeting']},{' '}
```
Comment (rschamp) [inline src/components/teacher-banner/teacher-banner.jsx]: These are still using dashes

File: src/lib/jar.js (hunk 1 above)
Comment (mewtaylor) [inline src/lib/jar.js]: I think leaving it in here is fine for now. While it doesn't really have to do with cookies per se, to me it does seem to be specific to the way _we_ do cookies at this point. So I don't see a reason to split it out, unless we see signing/unsigning as something that we will be doing in other places

**Comment by jwzimmer** [comment]
**Testing**

Chrome Version 51.0.2704.106 (64-bit)
- [ ] The banner is not present when I log out after logging in as a teacher
- [ ] The banner is not present when I log in as not-a-teacher
- [ ] The banner is not present when I log in as a student
- [x] The banner when I log in as a teacher looks like the mock-up Carl provided in https://github.com/LLK/scratch-www/issues/543
- [x] The banner persists after I go through the other pages in the nav bar (including editor)
- [x] The button for My Classes in the banner takes me to My Classes
- [x] The button for Educator Resources in the banner takes me to the Resources page
- [ ] **The button for Teacher Account FAQ takes me to FAQ**
  - Right now, the button redirects to the 404 page
screen shot 2016-06-29 at 11 05 32 am

**Comment by chrisgarrity** [comment]
Testing
Chrome Version 51.0.2704.103 (64-bit)
- [x] **The banner is not present when I log out after logging in as a teacher**
  - https://github.com/LLK/scratch-www/issues/626
- [x] **The button for Teacher Account FAQ takes me to FAQ**
  - https://github.com/LLK/scratch-www/issues/625

**Comment by jwzimmer** [comment]
Testing (Staging)
IE11 on Win7 Virtual Machine Version 20141027

- [ ] The banner is not present when I log out after logging in as a teacher
  - https://github.com/LLK/scratch-www/issues/626
- [ ] The banner is not present when I log in as not-a-teacher
- [ ] The banner is not present when I log in as a student
- [ ] The banner when I log in as a teacher looks like the mock-up Carl provided in https://github.com/LLK/scratch-www/issues/543
- [ ] The banner persists after I go through the other pages in the nav bar (including editor)
- [ ] The button for My Classes in the banner takes me to My Classes
- [ ] The button for Educator Resources in the banner takes me to the Resources page
- [ ] The button for Teacher Account FAQ takes me to FAQ
  - https://github.com/LLK/scratch-www/issues/625

**Comment by chrisgarrity** [comment]
**Testing**

Safari Version 9.1.1 (11601.6.17)

- [X] **The banner is not present when I log out after logging in as a teacher**
  - https://github.com/LLK/scratch-www/issues/626
- [x] The banner is not present when I log in as not-a-teacher
- [ ] The banner is not present when I log in as a student (I didn't have a student account)
- [x] The banner when I log in as a teacher looks like the mock-up Carl provided in https://github.com/LLK/scratch-www/issues/543
- [x] The banner persists after I go through the other pages in the nav bar (including editor)
- [x] The button for My Classes in the banner takes me to My Classes
- [x] The button for Educator Resources in the banner takes me to the Resources page
- [x] **The button for Teacher Account FAQ takes me to FAQ**
  - https://github.com/LLK/scratch-www/issues/625

**Comment by jwzimmer** [comment]
(The IE test cases are blocked for now by not being able to log-in: https://github.com/LLK/scratch-www/issues/654)

**Comment by jwzimmer** [comment]
Testing (Staging)
Edge on Win10TH Virtual Machine (on the QA machine)

- [ ] The banner is not present when I log out after logging in as a teacher
  - https://github.com/LLK/scratch-www/issues/626
- [ ] The banner is not present when I log in as not-a-teacher
- [ ] The banner when I log in as a teacher looks like the mock-up Carl provided in https://github.com/LLK/scratch-www/issues/543
- [ ] The banner persists after I go through the editor and back to the homepage
- [ ] The button for My Classes in the banner takes me to My Classes
- [ ] The button for Teacher Account FAQ takes me to FAQ
  - https://github.com/LLK/scratch-www/issues/625

**Comment by jwzimmer** [comment]
IE 11, Win 7 VM

* [x] I don't see the banner when I'm logged in as a student
* [x] I don't see the banner when I'm not logged in
* [x] I do see the banner when I am logged in as a teacher
* [x] The buttons in the banner take you to the right places
* [x] The banner looks approximately correct (I don't see any differences from what's expected)
