### PR TITLE
Fix gh-1183: Remove slashes

### LINKED ISSUE #1183: Footer links for www pages should not end in `/`
**TL;DR:** footer links for scratchr2 pages should end in `/`, but footer links for www pages should not.

Pretty much all the footer links for www pages need to be changed (remove the `/` at the end) other than `/developers`. 
`https://day.scratch.mit.edu` does not need to be changed. External links (ScratchEd, ScratchFoundation, etc.) don't need to be changed.

screen shot 2017-02-14 at 5 09 40 pm
screen shot 2017-02-14 at 5 09 15 pm
screen shot 2017-02-14 at 5 09 09 pm
screen shot 2017-02-14 at 5 09 04 pm
screen shot 2017-02-14 at 5 08 18 pm
screen shot 2017-02-14 at 5 08 00 pm
screen shot 2017-02-14 at 5 07 47 pm
screen shot 2017-02-14 at 5 07 40 pm
screen shot 2017-02-14 at 5 07 32 pm
screen shot 2017-02-14 at 5 07 22 pm

### PR DESCRIPTION
**Pull request by TheGrits**
Should fix #1183

### CODE REVIEW

File: src/components/footer/www/footer.jsx [hunk 1]
```diff
@@ -20,34 +20,34 @@ var Footer = React.createClass({
...
                             </dd>
                             <dd>
-                                <a href="/jobs/">
+                                <a href="/jobs">
                                     <FormattedMessage id='general.jobs' />
                                 </a>
                             </dd>
                             <dd>
-                                <a href="/contact-us/">
+                                <a href="/contact-us">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page – I think we want to leave the trailing slash in for this one.

File: src/components/footer/www/footer.jsx [hunk 2]
```diff
@@ -61,17 +61,17 @@ var Footer = React.createClass({
...
                             </dt>
                             <dd>
-                                <a href="/about/">
+                                <a href="/about">
                                     <FormattedMessage id='general.aboutScratch' />
                                 </a>
                             </dd>
                             <dd>
-                                <a href="/parents/">
+                                <a href="/parents">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page too.

File: src/components/footer/www/footer.jsx [hunk 3]
```diff
@@ -81,17 +81,17 @@ var Footer = React.createClass({
...
                             </dd>
                             <dd>
-                                <a href="/jobs/">
+                                <a href="/jobs">
                                     <FormattedMessage id='general.jobs' />
                                 </a>
                             </dd>
                             <dd>
-                                <a href="http://wiki.scratch.mit.edu/wiki/Scratch_Press">
+                                <a href="http://wiki.scratch.mit.edu/wiki/Scratch_Press/">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: Since this is an external link to the wiki, I think we should leave it as is (without the trailing slash)

File: src/components/footer/www/footer.jsx [hunk 4]
```diff
@@ -101,12 +101,12 @@ var Footer = React.createClass({
...
                             </dt>
                             <dd>
-                                <a href="/community_guidelines/">
+                                <a href="/community_guidelines">
                                     <FormattedMessage id='general.guidelines' />
                                 </a>
                             </dd>
                             <dd>
-                                <a href="/discuss/">
+                                <a href="/discuss">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page too.

File: src/components/footer/www/footer.jsx [hunk 5]
```diff
@@ -116,7 +116,7 @@ var Footer = React.createClass({
                                 </a>
                             </dd>
                             <dd>
-                                <a href="/statistics/">
+                                <a href="/statistics">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page too.

File: src/components/footer/www/footer.jsx [hunk 6]
```diff
@@ -127,22 +127,22 @@ var Footer = React.createClass({
                                 <FormattedMessage id='general.support' />
                             </dt>
                             <dd>
-                                <a href="/help/">
+                                <a href="/help">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page too.

File: src/components/footer/www/footer.jsx [hunk 7]
```diff
@@ -127,22 +127,22 @@ var Footer = React.createClass({
...
                             </dd>
                             <dd>
-                                <a href="/info/faq/">
+                                <a href="/info/faq">
                                     <FormattedMessage id='general.faq' />
                                 </a>
                             </dd>
                             <dd>
-                                <a href="/scratch2download/">
+                                <a href="/scratch2download">
```
Comment (mewtaylor) [inline src/components/footer/www/footer.jsx]: This still points to a scratchr2 page too.

**Comment by TheGrits** [comment]
@mewtaylor Done! Also, I added one at `contact-us` because it appears to still be a scratch2r page.

**Comment by mewtaylor** [comment]
@TheGrits nice catch, thanks :).
