### PR TITLE
Fix editor title when not logged in

### LINKED ISSUE #3798: The tab title of the editor is nothing when you are signed out.
The title of the tab of the editor is nothing when you are signed out.

### Steps to Reproduce

Sign out and [go to the editor](https://scratch.mit.edu/projects/editor/). The title of the tab is nothing. (depends on your browser, like on chrome it shows up as the URL of the tab, others as unnamed)

### Operating System and Browser

Windows NT 10.0, Chrome 81.0.4044.92

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves:
Resolves #3798 

### Changes:
Previously, if `projectInfo.author` is not available, there were no meta-tags. It was not a problem for logged-in users, because when they create new project, a new project is created immediately and author is passed. However, when not logged in, projects are not "created", so there is no author. In this case, check `userPresent` and if it doesn't exist, returns a helmet with `Scratch - Imagine, Program, Share` title. Other meta tags are omitted.

### Test Coverage:
Manually tested

### CODE REVIEW

File: src/views/preview/meta.jsx [hunk 1]
```diff
@@ -1,14 +1,23 @@
...
 
-    // Do not want to render any meta tags unless all the info is loaded
-    // Check only author (object) because it is ok to have empty string instructions
-    if (!author) return null;
+    if (!author) {
+        // Project info is not ready. It's either fetching state, or logged-out users creating project.
+        if (!props.userPresent) {
+            return (
+                <Helmet>
+                    <title>Scratch - Imagine, Program, Share</title>
```
Comment (adroitwhiz) [inline src/views/preview/meta.jsx:15]: Should this be localized?

Comment (apple502j) [reply src/views/preview/meta.jsx:15]: Currently, titles are not localized. It can be, but let's make another issue for that.

**Comment by benjiwheeler** [comment]
Thanks @apple502j!
