### PR TITLE
Search view fixes

### LINKED ISSUE #1189: Search bar not working - Staging
**TL;DR:** The API request is not getting the search query term.

Found while smoke-testing (https://github.com/LLK/scratchr2/issues/4457).

**Repro:**
- Go to staging
- Search for "duck"
- Search for "duck cat"
- Note the results are the same for either query, and don't seem relevant

### PR DESCRIPTION
**Pull request by rschamp**
* Fixes #1189: Wait for the search term prop before performing the search. Also encode the term sent to the API, so the API request uses a valid URL.
* Also fixes an unlogged error, the same as #1153, but from the search form on the search page (not in the nav bar).
* Finally, clean up keys to resolve warnings from React. There were so many on the search page that my browser was locking up (only affects development).

### CODE REVIEW

**Comment by thisandagain** [comment]
Thanks @rschamp . This LGTM.

File: src/views/search/search.jsx [hunk 1]
```diff
@@ -51,14 +51,16 @@ var Search = injectIntl(React.createClass({
...
             term = term.substring(0, term.indexOf('&'));
         }
-        term = term.split('+').join(' ');
-        this.getSearchMore();
-        this.props.dispatch(navigationActions.setSearchTerm(decodeURI(term)));
+        term = decodeURI(term.split('+').join(' '));
+        this.props.dispatch(navigationActions.setSearchTerm(term));
+    },
+    componentDidUpdate: function (nextProps) {
+        if (this.props.searchTerm !== nextProps.searchTerm) this.getSearchMore();
```
Comment (mewtaylor) [inline src/views/search/search.jsx]: I could be missing something – but won't `getSearchMore` in this instance be used on the existing `searchTerm`, whereas we want to use it on the new one?

Comment (rschamp) [inline src/views/search/search.jsx]: Fixed! Just called that argument the wrong thing.
